*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZSD_05_KEPOTOP.                   " Global Data
  INCLUDE LZSD_05_KEPOUXX.                   " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZSD_05_KEPOF00                         . " subprograms
  INCLUDE LZSD_05_KEPOI00                         . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZSD_05_KEPOF...                   " Subprograms
* INCLUDE LZSD_05_KEPOO...                   " PBO-Modules
* INCLUDE LZSD_05_KEPOI...                   " PAI-Modules

INCLUDE LZSD_05_KEPOF01.
